name: base
channels: [conda-forge]
channel_priority: strict
dependencies:
  - python=3.11
  - alembic
  - authlib
  - fastapi
  - celery
  - httpx
  - ipython
  - itsdangerous
  - jinja2
  - psycopg2
  - pytest
  - requests
  - sqlalchemy
  - uvicorn
  - passlib
  - sqlalchemy-utils
  - python-multipart
  - pyjwt
  - flower
  - redis-py
  - bcrypt=4.0.1
