name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge
      - name: Install dependencies
        run: |
          mamba env create -f {{cookiecutter.project_slug}}/backend/environment.yml
      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write **/*.{ts,tsx,md}
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: '{{cookiecutter.project_slug}}/backend --check --line-length 79'
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate {{cookiecutter.project_slug}}
          sudo ./scripts/test.sh